### ISSUE TITLE
Unable to download the s3dg weights

### ISSUE THREAD

**Issue by pankayaraj** [sumedh7/RoboCLIP#4]
I am unable to access the weights for s3dg model from here "https://www.rocq.inria.fr/cluster-willow/amiech/howto100m/s3d_howto100m.pth". Has the path for the weights been changed

**Comment by jesbu1** [comment]
They haven't replied, here's a link on my google drive: https://drive.google.com/file/d/1DN8t1feS0t5hYYTfXQfZd596Pu9yXJIr/view?usp=sharing

**Comment by jesbu1** [comment]
Here's the .npy: https://drive.google.com/file/d/1p_CMGppAQk3B0_Z0i1r2AN_D1FM3kUFW/view?usp=sharing

**Comment by pankayaraj** [comment]
Thanks a lot for sharing the weights
